// Board configuration selection for {{BOARD_DESCRIPTION}}
// 
// This file selects and re-exports the {{CHIP_NAME}} board configuration.
// Generated by setup.sh script.

// Include the base trait definitions  
#[path = "src/board/base.rs"]
mod base;

// Export the base traits for use by other modules
pub use base::{BoardConfiguration, InterruptHandlers};

// Include the {{CHIP_NAME}} board configuration
#[path = "src/board/{{BOARD_CONFIG_FILE}}"]
mod active_board;

// Re-export the active board configuration
pub use active_board::BoardConfig;
