// Board configuration selection for STM32F446RE Nucleo board
// 
// This file selects and re-exports the STM32F446RE board configuration.
// Generated by setup.sh script.

// Include the base trait definitions  
#[path = "src/boards/base.rs"]
mod base;

// Export the base traits for use by other modules
pub use base::{BoardConfiguration, InterruptHandlers};

// Include the STM32F446RE board configuration
#[path = "src/boards/nucleo_f446re.rs"]
mod active_board;

// Re-export the active board configuration
pub use active_board::BoardConfig;
