# config.toml template for MCU configuration
# Managed by setup script

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
linker = "arm-none-eabi-gcc"
runner = ["probe-rs", "run", "--chip", "{{CHIP_NAME}}", "--catch-hardfault", "--catch-reset", "--rtt-scan-memory", "--log-format=oneline"]

rustflags = [
  "-C", "linker=flip-link", # use flip-link as linker
  "-C", "link-arg=-Tlink.x", # linker script, linker.x
  "-C", "link-arg=-Tdefmt.x", # for defmt support
  "-C", "link-arg=--nmagic",  # avoids page alignment
]

[env]
DEFMT_LOG = "trace"

[build]
target = "thumbv7em-none-eabihf"

[alias]
rb = "run --bin"
rrb = "run --release --bin"
tests = "test --test integration"
